### ISSUE TITLE
Brakuje licencji

### ISSUE THREAD

**Issue by galuszkak** [qoobaa/slaskit.pl#6]
Jaka licencja jest używana? Ktoś chciał użyć tego skryptu ale niezbyt wiemy jaka jest licencja. :)

**Comment by qoobaa** [comment]
Hej,

chyba przegapiłem Twoje zgłoszenie, przepraszam. O jaki skrypt chodziło, o JS? Z tego co pamiętam to kilkadziesiąt linijek brzydkiego kodu w Angularze, więc nie sądzę żeby był komuś do czegoś przydatny. Jeśli temat jest nadal aktualny, to dodam `LICENSE`.
