### ISSUE TITLE
Stronka nie działa

### ISSUE THREAD

**Issue by afronski** [qoobaa/slaskit.pl#7]
Strona całkiem nie działa (`ERR_NAME_NOT_RESOLVED` - czy projekt jest zamknięty? :wink:

**Comment by qoobaa** [comment]
Cześć Wojtek,

wiem o problemie, dzięki za zgłoszenie i przypomnienie. Ze względu na jakiś tam błąd w OVH, domena nie przedłużyła się automatycznie i mi uciekła. Z tego co widzę, to przejął ją @szimek - nie wiem jakie ma plany co do projektu.

Pozdrawiam.

**Comment by qoobaa** [comment]
@afronski naprawione
